# Generated by Django 2.2.3 on 2019-07-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tble',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='tble',
            name='img3',
        ),
    ]
