# Generated by Django 2.2.3 on 2019-07-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190731_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tble',
            name='discription1',
        ),
        migrations.RemoveField(
            model_name='tble',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='tble',
            name='tittle1',
        ),
    ]
