# Generated by Django 2.2.3 on 2019-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190731_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='tble1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle1', models.CharField(default='', max_length=50)),
                ('discription1', models.CharField(default='', max_length=50)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
            ],
        ),
    ]
