# Generated by Django 2.2.3 on 2019-07-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tble1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tble1',
        ),
    ]
