# Generated by Django 2.2.3 on 2019-07-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tble1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tble1',
            name='tittle1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
