# Generated by Django 2.2.3 on 2019-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190731_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tble1',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tble1',
            name='tittle1',
            field=models.CharField(max_length=50),
        ),
    ]
