# Generated by Django 2.2.3 on 2019-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tble',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
