# Generated by Django 2.2.3 on 2019-08-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tble',
            name='discription',
            field=models.CharField(max_length=150),
        ),
    ]
