# Generated by Django 2.2.3 on 2019-09-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190828_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='backgroundimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brandimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Blogimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Projectimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Knowusimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Serviceimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Whatweimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Careersimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Aboutusimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
                ('Contactusimg', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='file')),
            ],
        ),
    ]
